name: hparam_project
channels:
    - defaults
dependencies:
    - numpy
    - pandas
    - matplotlib
    - jupyter
    - scikit-learn
    - pip
    - pip:
        - opencv-python
        - pytorch-lightning
        - ray[tune]
        - tqdm
        - boto3
