name: hparam_project
channels:
    - defaults
dependencies:
    - numpy
    - pandas
    - matplotlib
    - jupyter
    - scikit-learn
    - pip
    - pillow=9.2.0
    - pip:
        - opencv-python-headless
        - pytorch-lightning=1.6.5
        - ray[tune]
        - tqdm
