name: hparam_project
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.10
    - numpy
    - pandas
    - matplotlib
    - jupyter
    - scikit-learn
    - pytorch
    - torchvision
    - pip
    - pip:
        - opencv-python-headless
        - pytorch-lightning==1.6
        - ray[tune]
        - tqdm
        - boto3
