model_cfg:
  model_id: CNN2
  args:
    in_channels: 1
    n_classes: 10
    input_shape: [28, 28]
    ch1: 8
    ch2: 16
    ch3: 64
    lin1: 128
    batch_norm: True
    dropout: True

data_cfg:
  dataset_id: mnist
  train: True
  batch_size: 32
  num_workers: 8
  use_precomputed_split: True
  split_path: /home/alex/Documents/personal-projects/hyperparameter-tuning/splits

loss_cfg:
  loss_id: bce_with_logits_loss
  args:

optimizer_cfg:
  optimizer_id: adam
  args:
    lr: 0.001

flags:
  max_epochs: 20
  default_root_dir: ../hparam_results/


callbacks:
  - early_stop:
      monitor: 'val_loss'
      mode: 'min'
  - plot_metrics: