model_cfg:
  model_id: torch_classifier
  args:
    architecture_id: resnet18
    pretrained: True
    num_classes: 10
    num_input_channels: 1

data_cfg:
  dataset_id: mnist
  train: True
  batch_size: 16
  num_workers: 1

loss_cfg:
  loss_id: bce_with_logits_loss
  args:

optimizer_cfg:
  optimizer_id: adam
  args:
    lr: 0.001

flags:
  max_epochs: 10
  default_root_dir: ../hparam_results/

callbacks:
  - early_stop:
      monitor: 'val_loss'
      mode: 'min'
  - plot_metrics: