model_cfg:
  model_id: cnn2
  args:
    input_shape: [28, 28]
    in_channels: 1

data_cfg:
  dataset_id: mnist
  train: True
  batch_size: 4
  num_workers: 0

loss_cfg:
  loss_id: bce_with_logits_loss
  args:

optimizer_cfg:
  optimizer_id: adam
  args:
    lr: 0.001

flags:
  max_epochs: 10
  default_root_dir: ./

callbacks:
  - early_stop:
      monitor: 'val_loss'
      mode: 'min'
  - plot_metrics:
