training_cfg:
  model_cfg:
    model_id: CNN1
    args:
      input_shape: [28, 28]
      in_channels: 1

  data_cfg:
    dataset_id: mnist
    train: True
    batch_size: 128
    num_workers: 8

  loss_cfg:
    loss_id: bce_with_logits_loss
    args:

  optimizer_cfg:
    optimizer_id: adam
    args:

flags:
  max_epochs: 5